name: First Workflow
on: [push]

jobs:
  run-first-command:
    runs-on: ubuntu-latest
    steps:
      - name: Display some text
        run: echo "Some text"
      - name: Comman in Multiline
        run: |
          node -v
          npm -v